### ISSUE TITLE
Is there a mailing list or discussion group for PREESM?  Other than issues...

### ISSUE THREAD

**Issue by LowellHuawei** [preesm/preesm#123]
Other than the issues page, is there a mailing list or discussion group page for PREESM?

I have numerous questions and would like to search earlier discussions before pestering people with posted issues.

The first question is, "What is the best document to read to learn how to use PREESM?"

**Comment by kdesnos** [comment]
Dear Lowel,

There exists the contact@preesm.insa-rennes.fr mailing list, to be used for private information requests to Preesm core team.

Otherwise, GitHub issues are, at the moment, the best place for questions/discussions to the community benefit from them. Don't be afraid to ask your numerous question, the worst that could happen is that we take some time to answer them :).

About your question 
> What is the best document to read to learn how to use PREESM?

The best way to do so is to follow the [tutorials](https://preesm.github.io/tutos/) from our website, which cover both the basic usage of the tool, as well as its more advanced features.
Additional documentations, including developper's guide and some documentations on the configurations of workflow tasks in Preesm can be found here: https://preesm.github.io/docs/
Finally, for more theoretical and scientific details on how the core features of Preesm and Spider are implemented, a list of all related scientific publications is available here: https://preesm.github.io/publis/.
