### ISSUE TITLE
Monitoring an hierarchical actor with PAPIFY

### ISSUE THREAD

**Issue by leos313** [preesm/preesm#188]
Is there a way of monitoring (measuring time) hierarchical actor of the PiSDF?
The PAPIFY tab gives me the possibility of selecting just the top of a hierarchical actor but it does actually nothing.

**Comment by dmadronal** [comment]
Hi,

You can monitor all the actors contained in the hierarchical actor but not the complete hierarchical actor as a whole.

By monitoring all the actors inside a hierarchical actors (or only the first and the last ones) you can compute the timing of the whole hierarchical actor manually or using PAPIFY-VIEWER.

**Comment by leos313** [comment]
Nope: there is the overhead of writing the file in the middle. For example:

```
#ifdef _PREESM_PAPIFY_MONITOR
event_stop_papify_timing(&papify_actions_nelderMeadCore_0_Centroid_0,0/*PE_id*/); // nelderMeadCore_0_Centroid_0
event_write_file(&papify_actions_nelderMeadCore_0_Centroid_0,0/*PE_id*/); // nelderMeadCore_0_Centroid_0
#endif
```

**Comment by dmadronal** [comment]
If you want to not consider this overhead, then, you should monitor everything inside the hierarchical actor and add up all the partial results.

**Comment by leos313** [comment]
nope: many of them are executed in parallel in different PE. 
What I can do, and I do, is to insert manually the instruction where is necessary. The question was exactly if there is an automated mechanism that I wasn't using properly!

**Comment by dmadronal** [comment]
Hi again,

As mentioned in the first comment, the monitoring of a hierarchical actor as a whole is not supported right now. Since PAPIFY instructions are inserted during the code generation workflow task, at this point, the algorithm network is already flattened and the monitoring is performed in an "atomic actor" way.

In the scenario tab, the hierarchy is shown so as to ease and speed up the monitoring configuration.

Best,

Dani

**Comment by leos313** [comment]
yeah! If the question has no sense and the feature will not be planned I think we can close the issue, right?
Thank you for answering!
Best 
Leos
