### ISSUE TITLE
WHILE loop implementation in PREESM

### ISSUE THREAD

**Issue by Martayugui** [preesm/preesm#209]
I am working on the parallelization of  an algorithm in PREESM. I would like to implement a WHILE loop which requires many iterations to converge (not iteration fixed a priori). So far, I have not seen any way to implement a loop with no number of tokens fixed a priori. Could I develop it in PREESM?

Thank you in advance, 

Marta

**Comment by orlyn44** [comment]
Doing a while loop is not possible in PREESM because it is not a predictable context. You can describe loop with the number of iteration being resolved at runtime using dynamic parameters but while loop is not possible.  However, you can describe the inner body of your loop with PREESM to have the schedule and the parallelism benefits from a dataflow modeling and call the generated code from a while loop. 
In this sense, you would be using PREESM to do software acceleration of a particular task of your application.
