### ISSUE TITLE
DEBUG messages on console: "We could not add overhead."

### ISSUE THREAD

**Issue by leos313** [preesm/preesm#228]
When executing a workflow, tens of such kind of line are printed:
```
15:23:10 DEBUG: The transfer following vertexFilter_251(Core3:Hardware,1121362,-1,100)was not found. We could not add overhead.
15:23:10 DEBUG: The transfer following vertexFilter_252(Core4:Hardware,1121362,-1,100)was not found. We could not add overhead.
15:23:10 DEBUG: The transfer following vertexFilter_253(Core5:Hardware,1121362,-1,100)was not found. We could not add overhead.
15:23:10 DEBUG: The transfer following vertexFilter_254(Core6:Hardware,1121362,-1,100)was not found. We could not add overhead.
```
What does that mean? Can I do something to fix it?

**Comment by antoine-morvan** [comment]
Those are DEBUG logging entries, only shown when you configure the workflow to show all entries (see https://preesm.github.io/release-3.3.0/).

They are most likely thrown because the scheduler/mapper, configured with LosselyTimed/AccuratelyTimed simulator type, was not able to retrieve timings for the transfer edges.
