### ISSUE TITLE
Initialization of delay tokens

### ISSUE THREAD

**Issue by jheulot** [preesm/preesm#24]
It would be nice to have the possibility to initialize delay token by a configure actor or interface. It will simplify many feedback looped graphs.

**Comment by antoine-morvan** [comment]
See #45

**Comment by Martayugui** [comment]
@antoine-morvan, given that there is no implementation yet (#45), is there any work-around to perform the initialization of a delay? I am trying to implement iterative loops and I cannot find the way.

**Comment by antoine-morvan** [comment]
There is support for delay initialization since version 2.14.0 https://github.com/preesm/preesm/releases/tag/v2.14.0
Theory is described in this paper : https://hal.inria.fr/hal-01850252
The graph editor still has some issues handling this kind of setup (see https://github.com/preesm/preesm/issues/83 for instance).
