### ISSUE TITLE
Expression of timings of a scenario use the parameters of the graph instead of the parameter of the actor

### ISSUE THREAD

**Issue by tbourgoi** [preesm/preesm#338]
Expressions in the "Timing" tab of a scenario use the names of the graph's parameters and not the names of actor's input parameters.

In the following example, if I want to set the timing of the actor Sobel based on the height of the image processed, I should use '**sliceHeight**' in the expression instead of '**height**'. If I use '**height**' in this case it would take the value of the parameter '**height**' of the graph and not the value of the input parameter. This is shown on the second screenshot. The time to execute the actor sobel is 288 in the gantt but the expression show that it should be 74.

![image](https://user-images.githubusercontent.com/45673674/123055049-c5007a80-d405-11eb-96be-e29122a8a475.png)

![image](https://user-images.githubusercontent.com/45673674/123054502-35f36280-d405-11eb-8849-4051933e5ea2.png)

**Comment by ahonorat** [comment]
Hello @tbourgoi ,

it sounds like a normal behavior to me.

Indeed the name of the Configuration Input Port (CIP) of Actor Sobel is "height" although it is dependent on parameter "sliceHeight", itself dependent on parameter "height".
The PREESM expression resolution in actor rates, timings and energy, starts by looking for CIP of the actor having the same name as in the expression. Here CIP name is "height" and is linked to the value of parameter "sliceHeight" inside the expression.
I guess you got confused because of the misleading parameter name overloading. 

Then in the specific case of timings and energy, and only if PREESM did not find any matching CIP, PREESM looks for a graph parameter having the same name as in the expression.
Hence in your example both "sliceHeight" and "height" in the timing expression of actor Sobel are resolved to the same parameter "sliceHeight" (the first one directly, with a warning, and the second one through the CIP which is the normal behavior).
I introduced this extra resolution because some actors may not need a parameter in their rate expressions or as an argument but still need it for their timing (e.g. a parameter giving the processor frequency). In such case, no CIP needs to be added.

I've attached another PREESM project to demonstrate this behavior.

[issue338.zip](https://github.com/preesm/preesm/files/7163234/issue338.zip)
