### ISSUE TITLE
Scenario constraints for broadcat actors are not taken into account 

### ISSUE THREAD

**Issue by ahonorat** [preesm/preesm#85]
In the scenario, if specifying core allocation constraints for broadcast, they are not taken into account by the scheduler. For example if a broadcast is specified to run on no core at all, the workflow will pursue without noticing it.

Two solutions, the second seems more plausible:
- take these constraints into account, although they are not really useful/meaningful for broadcasts;
- hide special actors in the "Constraints" tab of scenarii so that they cannot have any constraint.

**Comment by orlyn44** [comment]
@ahonorat hiding special actors may not be ideal as there can be a valid reason as to why put a constraint on it. At least for broadcast actors. You could imagine an architecture where one of the core is more suitable to deal with memory access than the others. 
Example: on the MPPA, putting a broadcast on a cluster instead of the IO core will result in poor performance for the memcpy due to the latency of having to access the DDR3 memory.
